REBASE: feat(mock-server)!: First full implementation
TelestionTeam/telestion-client pull request #437
Opened 2021-03-27 17:44 UTC by fussel178

### Summary 

First complete implementation of the Vert.x mock server with improved abstractions and hooks.

### Details 

- new abstractions and hooks
- better/more documentation

### Additional information 

#### BREAKING CHANGES:
- The listen function now requires an object as argument which contains the port and hostname as properties.
- The event bus and http server instance properties are now marked private. Please use the provided abstractions and hooks instead. (see onInit, send, handle, register, etc.)

### Related links 

- Fixes #264 
- Fixes #273 

### CLA

- [x] I have signed the individual contributor's license agreement **and sent** it to the board of the WüSpace e. V. organization.

2021-03-28 23:59 UTC, pklaschka requested changes
Overall, it looks good. I've left a few inline suggestions for some typos and other optimizations. 😉 

### One "major" request
Can we please make the logging optional? The solution doesn't have to be pretty, but I'd like to have the option of not polluting the console output in plugins and such.

2021-03-28 23:59 UTC, pklaschka commented on jest.config.js
> +		// 	]
Could you please add a `// TODO:` item here for what to do before uncommenting this section (adding an explanation of why it's commented out in the process)?

2021-03-28 23:59 UTC, pklaschka commented on packages/vertx-mock-server/src/model/callback.ts
> + * when the Vertx. mock server receives
```suggestion
 * when the Vert.x mock server receives
```

2021-03-28 23:59 UTC, pklaschka commented on packages/vertx-mock-server/src/model/callback.ts
> + * when the Vertx. mock server receives
```suggestion
 * when the Vert.x mock server receives
```

2021-03-28 23:59 UTC, pklaschka commented on packages/vertx-mock-server/src/model/extensions.ts
> +	 * and all {@link MockServer.register} calls has taken place.
```suggestion
	 * and all {@link MockServer.register} calls have taken place.
```

2021-03-28 23:59 UTC, pklaschka commented on packages/vertx-mock-server/src/model/extensions.ts
> + * and all {@link MockServer.register} calls has taken place.
```suggestion
 * and all {@link MockServer.register} calls have taken place.
```

2021-03-28 23:59 UTC, pklaschka commented on packages/vertx-mock-server/src/vertx-mock-server.ts
> +	 * Holds all active connections with the Vert.x mock server.
```suggestion
	 * Holds all active connections of the Vert.x mock server.
```

2021-03-28 23:59 UTC, pklaschka commented on packages/vertx-mock-server/src/vertx-mock-server.ts
> +	 * Starts the Vert.x mock server and listening for incoming connections.
```suggestion
	 * Starts the Vert.x mock server, listening for incoming connections.
```

2021-03-28 23:59 UTC, pklaschka commented on packages/vertx-mock-server/src/vertx-mock-server.ts
> +	 * and close currently active connections.
```suggestion
	 * Stops the server from accepting new connections
	 * and closes currently active connections.
```

2021-03-28 23:59 UTC, pklaschka commented on packages/vertx-mock-server/src/vertx-mock-server.ts
> +	 * @param channel - the channel the message are sent to
```suggestion
	 * @param channel - the channel the message gets sent to
```

2021-03-28 23:59 UTC, pklaschka commented on packages/vertx-mock-server/src/vertx-mock-server.ts
> +	 * @param message - the message that are sent over the specified channel
```suggestion
	 * @param message - the message that gets sent over the specified channel
```

2021-03-28 23:59 UTC, pklaschka commented on packages/vertx-mock-server/src/vertx-mock-server.ts
> +	 * @param error - the message that are sent over the specified channel
```suggestion
	 * @param channel - the channel the message gets sent to
	 * @param error - the message that gets sent over the specified channel
```

2021-03-28 23:59 UTC, pklaschka commented on packages/vertx-mock-server/src/vertx-mock-server.ts
> +	 * @param channel - the channel the callback is registered to
```suggestion
	 * @param channel - the channel the callback gets registered to
```

2021-03-28 23:59 UTC, pklaschka commented on packages/vertx-mock-server/src/vertx-mock-server.ts
> +	 * @param id - the callback id from the {@link MockServer.register} function
```suggestion
	 * @param id - the callback id returned by the {@link MockServer.register} function
```

2021-03-28 23:59 UTC, pklaschka commented on packages/vertx-mock-server/src/vertx-mock-server.ts
> +	 * Pushes a raw/encoded message onto a active connections.
```suggestion
	 * Pushes a raw/encoded message onto all active connections.
```

2021-03-28 23:59 UTC, pklaschka commented on packages/vertx-mock-server/src/vertx-mock-server.ts
> +	 * @param prefix - the prefix under which the event bus is reachable
```suggestion
	 * Set up the internal event bus, register all necessary event calls
	 * for incoming connections and attach it to the internal HTTP server instance.
	 *
	 * @param prefix - the prefix under which you can reach the event bus
```

2021-03-28 23:59 UTC, pklaschka commented on packages/vertx-mock-server/src/vertx-mock-server.ts
> +	 * @see {@link MockServer.setupEventBus}
```suggestion
	 * Handles the incoming data, decodes them, sorts them
	 * and calls the registered callbacks.
	 *
	 * @param conn - the connection the message came from
	 * @param data - the raw/encoded message
	 *
	 * @see {@link MockServer.setupEventBus}
```

2021-03-28 23:59 UTC, pklaschka commented on packages/vertx-mock-server/src/vertx-mock-server.ts
> +	 * @see {@link MockServer.setupEventBus}
```suggestion
	 * Handles the closed event on the current connection.
	 * Removes the given connection from the connection list
	 * and calls the connection closed hook.
	 *
	 * @param conn - the closed connection
	 *
	 * @see {@link MockServer.setupEventBus}
```

2021-03-28 23:59 UTC, pklaschka commented on packages/vertx-mock-server/src/vertx-mock-server.ts
> +	 * and call all registered callbacks on the message channel.
```suggestion
	 * Processes the received message, determines the type,
	 * builds the arguments for the callbacks
	 * and calls all registered callbacks on the message channel.
```

2021-03-28 23:59 UTC, pklaschka commented on packages/vertx-mock-server/src/vertx-mock-server.ts
> +	 * @param message - the 'send' message to build the respond handler for
```suggestion
	 * Builds the `respond` handler for a 'send' message.
	 * @param conn - the connection the message came from
	 * @param message - the 'send' message for which the `respond` handler gets built
```

2021-03-30 05:20 UTC, fussel178 commented
Now you can set a `ComponentLogger` in the constructor where the mock server and the SockJS server log it contents.
I also improved the current log output by a lot.

![image](https://user-images.githubusercontent.com/52416718/112937704-a6952680-9117-11eb-977e-bb9e9369cf30.png)

2021-03-30 10:58 UTC, pklaschka approved these changes
LGTM! 🎉 👍

2021-03-30 12:39 UTC, merged